Only measure code coverage in one configuration of the CI matrix
We don't need to measure coverage for each run since we don't have logic
that's conditional on the ruby version or the rack version. Furthermore,
it seems like when all of the jobs try to upload the coverage artifact,
some of them fail with
```
Error: Unexpected response. Unable to upload chunk to https://pipelines.actions.githubusercontent.com/Rno49s13pA5vllnyZeZXc7qQF0b4Jq8BZ4WgDbFQX4NocZwQsY/_apis/resources/Containers/14397?itemPath=code-coverage-report%2Fassets%2F0.12.3%2Fcolorbox%2Floading.gif
```
as seen in
https://github.com/miyagawa/rack-vcr/runs/1337619960?check_suite_focus=true

So, let's only measure coverage for the job running the latest ruby and
rack versions.